sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t alex-x-st/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true alex-x-st/react-test npm test

after_success:
  - docker build -t alex-x-st/multi-client ./client
  - docker build -t alex-x-st/multi-nginx  ./nginx
  - docker build -t alex-x-st/multi-server ./server
  - docker build -t alex-x-st/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push images to docker hub
  - docker push alex-x-st/multi-client
  - docker push alex-x-st/multi-nginx
  - docker push alex-x-st/multi-server
  - docker push alex-x-st/multi-worker
